### ISSUE TITLE
[Feature Request]: Need the functionality so that user can upload their photos and they can be converted into a QR code.

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Generate-QR-code#4]
I have seen QR codes that can contain pictures. When someone scans that QR code, a photo shows up. We need to add that function to the app.

**Comment by Sar-thak-3** [comment]
@Manobal-Singh-Bagady I read a lot of papers regarding this, and I believe that images can't be converted to QR because data on images are huge, hence we can do store some uploaded images on any online database. Like 5/10 photos at a time in database if new user upload image then previous 10th image will get deleted from database and we can store link for that image on QR.

**Comment by ugpec79** [comment]
@Manobal-Singh-Bagady why not create a qr with link of uploaded photos with different cloud services

**Comment by ugpec79** [comment]
@Manobal-Singh-Bagady pls assign this to me

**Comment by Manobal-Singh-Bagady** [comment]
Yes @Sar-thak-3 I was thinking the same about it, a database will definitely be needed. If you can implement it It would be perfect.

**Comment by Manobal-Singh-Bagady** [comment]
I'm assigning this issue to both you @Sar-thak-3 and @ugpec79
